name: proyecto_integrador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  url_launcher: ^6.1.7
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  flutter_datetime_picker: ^1.5.1
  workmanager: ^0.5.2  # Cambia a la versi칩n compatible 0.5.2
  flutter_local_notifications: ^14.1.5
  timezone: ^0.9.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.69.2
  table_calendar: ^3.0.5
  pedometer: ^4.0.2
  mobile_scanner: ^6.0.2
  flutter_tts: ^4.2.0
  google_generative_ai: ^0.4.6  # Requiere http ^1.1.0
  http: ^1.1.0                  # Versi칩n compatible con google_generative_ai
  intl: ^0.17.0  # Cambiado a una versi칩n compatible con charts_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo1.png
    - assets/Ovalo.png
    - assets/Bienvenidos.png
    - assets/TareasHome.png
    - assets/ComunidadHome.png
    - assets/GraficasHome.png
    - assets/ChatBot.png
    - assets/FireHome.png
    - assets/Emociones.png
    - assets/Pasos.png
    - assets/Sue침o.png
    - assets/coins.png
    - assets/FireBlue.png
